services:
  aistablediffusion:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ai_stable_diffusion
    restart: unless-stopped
    environment:
      - TZ=America/Sao_Paulo
    # volumes:
    #   - ./outputs:/app/outputs
    networks:
      - net_sd_diff
    ports:
      - "22:22"
      - "7861:7860"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

networks:
  net_sd_diff:
    name: net_sd_diff
    driver: bridge